name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apk add build-base git zip

      - name: Clone GSKit
        run: |
          git clone https://github.com/ps2dev/gskit.git
          cd gskit
          make install
          cd ..

      - name: Fetch full history
        run: git fetch --prune --unshallow

      - name: Compile
        run: make

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: main_${{ env.sha8 }}
          path: main.elf
