name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:v1.2.0
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: apk add build-base git zip cmake make

      - name: Ensure Toolchain File
        run: |
          if [ ! -f /usr/local/ps2dev/ps2sdk/ps2dev.cmake ]; then
            git clone https://github.com/ps2dev/ps2sdk.git /tmp/ps2sdk
            cp /tmp/ps2sdk/ps2dev.cmake /usr/local/ps2dev/ps2sdk/ps2dev.cmake
          fi

      - name: Clone and Build PS2SDK Ports
        run: |
          git clone https://github.com/ps2dev/ps2sdk-ports.git
          cd ps2sdk-ports
          make
          make install
          cd ..

      - name: Clone GSKit
        run: |
          git clone https://github.com/ps2dev/gskit.git
          cd gskit
          cmake -S . -B build -Wno-dev \
            "-DCMAKE_TOOLCHAIN_FILE=/usr/local/ps2dev/ps2sdk/ps2dev.cmake" \
            "-DCMAKE_INSTALL_PREFIX=/usr/local/ps2dev/ps2sdk/ports" \
            -DCMAKE_MAKE_PROGRAM=$(which make) \
            -DCMAKE_C_COMPILER=ee-gcc \
            -DCMAKE_CXX_COMPILER=ee-g++ \
            -DBUILD_SHARED_LIBS=OFF \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            "-DCMAKE_PREFIX_PATH=/usr/local/ps2dev/ps2sdk/ports"
          make -C build
          make -C build install
          cd ..

      - name: Fetch full history
        run: git fetch --prune --unshallow

      - name: Compile Project
        run: make

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: main_${{ env.sha8 }}
          path: main.elf
